### ISSUE TITLE
Sample application

### ISSUE THREAD

**Issue by philjoseph** [jwoolston/Android-Webcam#8]
Hello JWoolston - we are interested to try to your pure Java driver for UVC camera. Do you have a sample app that can show concrete usage of the driver ?

**Comment by ToxicBakery** [comment]
This lib does not actually do anything *yet* but one day it might. The biggest hurdle is properly talking to a web cam given limitations of what Android lets you do with the OTG port.

**Comment by philjoseph** [comment]
Thanks for the answer. I wonder how more complex it is to communicate with a UVC from android compared to a windows app. I have a client that is very interested to resolve that and would be glad to obtain more help. Let me know if we can discuss this offline (philc@shefing.com).
